site_name: AName
pages:
- [index.md, Home]
- [about.md, About,'Collection']
- [test1.md, Test]
theme: mkdocs
repo_url: https://github.com/example/repository/
site_description: 
site_author: 
site_favicon: 
docs_dir: docs
site_dir: site
dev_addr: 127.0.0.1:8000