site_name: LimeBootstrap
pages:
- [index.md, 'About']
- [philosophy.md, 'Philosophy']
- [basicUsage.md, 'BasicUsage']
- [advanced.md, 'Advanced']
- [buildingApps.md, 'BuildingApps']
- [changelog.md, 'Changelog']
- [technicalPlatform.md, 'TechnicalPlatform']
- [python.md, 'Python - Installation and configuration']
theme: readthedocs
repo_url: https://github.com/Lundalogik/LimeBootstrapServices
site_description: LimeBootstrap dokumentation
site_author: Lundalogik AB
site_favicon: 
docs_dir: docs
site_dir: ..\web\manual
dev_addr: 127.0.0.1:8000